/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.6.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLayout>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QToolBox>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QFrame *line;
    QFrame *line_2;
    QLabel *gavsLabel;
    QToolButton *tab1;
    QToolButton *tab2;
    QGroupBox *groupBox;
    QToolBox *toolBox;
    QWidget *page_2;
    QFrame *frame_2;
    QLineEdit *simple_val;
    QPushButton *pushButton;
    QWidget *widget_2;
    QRadioButton *radioX;
    QRadioButton *radioY;
    QLabel *label_5;
    QLineEdit *simple_axis;
    QLabel *label_6;
    QFrame *frame_5;
    QWidget *page_3;
    QWidget *widget_3;
    QRadioButton *radioFilled;
    QRadioButton *radioHollow;
    QFrame *frame_3;
    QLineEdit *cY;
    QLabel *label_9;
    QLabel *label_11;
    QLineEdit *radiusBox;
    QLineEdit *rV0_Box;
    QPushButton *pushButton_3;
    QLabel *label_10;
    QLabel *label_8;
    QLineEdit *cX;
    QLabel *label_12;
    QWidget *page_4;
    QPushButton *recButoon;
    QRadioButton *radioHollow_2;
    QLabel *label_15;
    QLineEdit *width;
    QLineEdit *length;
    QLabel *label_16;
    QLabel *label_14;
    QLabel *label_19;
    QLineEdit *rX;
    QRadioButton *radioFilled_2;
    QLabel *label_13;
    QLineEdit *recV0;
    QLineEdit *rY;
    QLabel *label_18;
    QWidget *page_6;
    QPushButton *digButton_2;
    QLineEdit *digV0_2;
    QLabel *label_27;
    QLineEdit *dy_2;
    QLineEdit *dx_2;
    QLineEdit *dy_1;
    QLineEdit *dx_3;
    QLabel *dx_4;
    QLabel *label_29;
    QLabel *dx_1;
    QLabel *label_28;
    QLabel *label_21;
    QWidget *page_5;
    QPushButton *digButton;
    QLabel *label_24;
    QLineEdit *digV0;
    QLabel *label_26;
    QLineEdit *dm;
    QLabel *label_25;
    QLineEdit *dc;
    QLabel *label_22;
    QLabel *label_20;
    QWidget *page;
    QLabel *label_31;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_7;
    QLabel *label_17;
    QLabel *label_23;
    QLineEdit *quadA;
    QLineEdit *quadB;
    QLineEdit *quadC;
    QLabel *label_32;
    QLineEdit *quadV0;
    QPushButton *pushButton_5;
    QPushButton *pushButton_4;
    QLabel *label_4;
    QFrame *frame;
    QRadioButton *radioM;
    QRadioButton *radioJ;
    QRadioButton *radioG;
    QRadioButton *radioS;
    QLabel *label_3;
    QLineEdit *size;
    QProgressBar *gavsBar;
    QLineEdit *looper;
    QPushButton *pushButton_2;
    QLabel *label_30;
    QPushButton *interact;
    QLabel *origin;
    QLabel *maxX;
    QLabel *maxY;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1059, 894);
        MainWindow->setAutoFillBackground(false);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        line = new QFrame(centralWidget);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(470, 0, 20, 861));
        line->setFrameShape(QFrame::VLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(centralWidget);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(490, 260, 951, 20));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        gavsLabel = new QLabel(centralWidget);
        gavsLabel->setObjectName(QStringLiteral("gavsLabel"));
        gavsLabel->setGeometry(QRect(520, 320, 500, 500));
        tab1 = new QToolButton(centralWidget);
        tab1->setObjectName(QStringLiteral("tab1"));
        tab1->setGeometry(QRect(750, 800, 31, 29));
        tab2 = new QToolButton(centralWidget);
        tab2->setObjectName(QStringLiteral("tab2"));
        tab2->setGeometry(QRect(780, 800, 31, 29));
        groupBox = new QGroupBox(centralWidget);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(260, 30, 191, 171));
        toolBox = new QToolBox(centralWidget);
        toolBox->setObjectName(QStringLiteral("toolBox"));
        toolBox->setGeometry(QRect(20, 10, 451, 731));
        page_2 = new QWidget();
        page_2->setObjectName(QStringLiteral("page_2"));
        page_2->setGeometry(QRect(0, 0, 451, 521));
        frame_2 = new QFrame(page_2);
        frame_2->setObjectName(QStringLiteral("frame_2"));
        frame_2->setGeometry(QRect(280, 20, 141, 101));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        simple_val = new QLineEdit(page_2);
        simple_val->setObjectName(QStringLiteral("simple_val"));
        simple_val->setGeometry(QRect(70, 70, 131, 33));
        pushButton = new QPushButton(page_2);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(320, 170, 95, 31));
        widget_2 = new QWidget(page_2);
        widget_2->setObjectName(QStringLiteral("widget_2"));
        widget_2->setGeometry(QRect(290, 30, 120, 80));
        radioX = new QRadioButton(widget_2);
        radioX->setObjectName(QStringLiteral("radioX"));
        radioX->setGeometry(QRect(10, 50, 110, 26));
        radioY = new QRadioButton(widget_2);
        radioY->setObjectName(QStringLiteral("radioY"));
        radioY->setGeometry(QRect(10, 10, 110, 26));
        label_5 = new QLabel(page_2);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(10, 20, 41, 21));
        simple_axis = new QLineEdit(page_2);
        simple_axis->setObjectName(QStringLiteral("simple_axis"));
        simple_axis->setGeometry(QRect(70, 20, 131, 33));
        label_6 = new QLabel(page_2);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(20, 70, 21, 21));
        frame_5 = new QFrame(page_2);
        frame_5->setObjectName(QStringLiteral("frame_5"));
        frame_5->setGeometry(QRect(280, 20, 141, 101));
        frame_5->setFrameShape(QFrame::StyledPanel);
        frame_5->setFrameShadow(QFrame::Raised);
        toolBox->addItem(page_2, QStringLiteral("Simple Bound"));
        frame_5->raise();
        frame_2->raise();
        simple_val->raise();
        pushButton->raise();
        widget_2->raise();
        label_5->raise();
        simple_axis->raise();
        label_6->raise();
        page_3 = new QWidget();
        page_3->setObjectName(QStringLiteral("page_3"));
        widget_3 = new QWidget(page_3);
        widget_3->setObjectName(QStringLiteral("widget_3"));
        widget_3->setGeometry(QRect(300, 30, 151, 111));
        radioFilled = new QRadioButton(widget_3);
        radioFilled->setObjectName(QStringLiteral("radioFilled"));
        radioFilled->setGeometry(QRect(30, 60, 110, 26));
        radioHollow = new QRadioButton(widget_3);
        radioHollow->setObjectName(QStringLiteral("radioHollow"));
        radioHollow->setGeometry(QRect(30, 20, 110, 26));
        frame_3 = new QFrame(widget_3);
        frame_3->setObjectName(QStringLiteral("frame_3"));
        frame_3->setGeometry(QRect(-1, 10, 141, 81));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Raised);
        frame_3->raise();
        radioHollow->raise();
        radioFilled->raise();
        cY = new QLineEdit(page_3);
        cY->setObjectName(QStringLiteral("cY"));
        cY->setGeometry(QRect(200, 50, 41, 31));
        label_9 = new QLabel(page_3);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(180, 50, 21, 21));
        label_11 = new QLabel(page_3);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(30, 100, 51, 21));
        radiusBox = new QLineEdit(page_3);
        radiusBox->setObjectName(QStringLiteral("radiusBox"));
        radiusBox->setGeometry(QRect(120, 100, 111, 33));
        rV0_Box = new QLineEdit(page_3);
        rV0_Box->setObjectName(QStringLiteral("rV0_Box"));
        rV0_Box->setGeometry(QRect(120, 150, 111, 33));
        pushButton_3 = new QPushButton(page_3);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(310, 200, 95, 31));
        label_10 = new QLabel(page_3);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(20, 50, 66, 21));
        label_8 = new QLabel(page_3);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(100, 50, 21, 21));
        cX = new QLineEdit(page_3);
        cX->setObjectName(QStringLiteral("cX"));
        cX->setGeometry(QRect(120, 50, 41, 31));
        label_12 = new QLabel(page_3);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(30, 160, 21, 21));
        toolBox->addItem(page_3, QStringLiteral("Radial Bound"));
        page_4 = new QWidget();
        page_4->setObjectName(QStringLiteral("page_4"));
        recButoon = new QPushButton(page_4);
        recButoon->setObjectName(QStringLiteral("recButoon"));
        recButoon->setGeometry(QRect(320, 200, 95, 31));
        radioHollow_2 = new QRadioButton(page_4);
        radioHollow_2->setObjectName(QStringLiteral("radioHollow_2"));
        radioHollow_2->setGeometry(QRect(320, 60, 110, 26));
        label_15 = new QLabel(page_4);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(80, 40, 21, 21));
        width = new QLineEdit(page_4);
        width->setObjectName(QStringLiteral("width"));
        width->setGeometry(QRect(90, 150, 111, 33));
        length = new QLineEdit(page_4);
        length->setObjectName(QStringLiteral("length"));
        length->setGeometry(QRect(90, 110, 111, 33));
        label_16 = new QLabel(page_4);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(10, 40, 66, 21));
        label_14 = new QLabel(page_4);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(160, 40, 21, 21));
        label_19 = new QLabel(page_4);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(20, 150, 51, 21));
        rX = new QLineEdit(page_4);
        rX->setObjectName(QStringLiteral("rX"));
        rX->setGeometry(QRect(100, 40, 41, 31));
        radioFilled_2 = new QRadioButton(page_4);
        radioFilled_2->setObjectName(QStringLiteral("radioFilled_2"));
        radioFilled_2->setGeometry(QRect(320, 100, 110, 26));
        label_13 = new QLabel(page_4);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(20, 200, 21, 21));
        recV0 = new QLineEdit(page_4);
        recV0->setObjectName(QStringLiteral("recV0"));
        recV0->setGeometry(QRect(90, 200, 111, 33));
        rY = new QLineEdit(page_4);
        rY->setObjectName(QStringLiteral("rY"));
        rY->setGeometry(QRect(180, 40, 41, 31));
        label_18 = new QLabel(page_4);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(20, 110, 51, 21));
        toolBox->addItem(page_4, QStringLiteral("Rectangular Bound"));
        page_6 = new QWidget();
        page_6->setObjectName(QStringLiteral("page_6"));
        digButton_2 = new QPushButton(page_6);
        digButton_2->setObjectName(QStringLiteral("digButton_2"));
        digButton_2->setGeometry(QRect(320, 170, 95, 31));
        digV0_2 = new QLineEdit(page_6);
        digV0_2->setObjectName(QStringLiteral("digV0_2"));
        digV0_2->setGeometry(QRect(140, 130, 131, 33));
        label_27 = new QLabel(page_6);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(60, 40, 31, 21));
        dy_2 = new QLineEdit(page_6);
        dy_2->setObjectName(QStringLiteral("dy_2"));
        dy_2->setGeometry(QRect(230, 80, 41, 31));
        dx_2 = new QLineEdit(page_6);
        dx_2->setObjectName(QStringLiteral("dx_2"));
        dx_2->setGeometry(QRect(90, 40, 41, 31));
        dy_1 = new QLineEdit(page_6);
        dy_1->setObjectName(QStringLiteral("dy_1"));
        dy_1->setGeometry(QRect(230, 40, 41, 31));
        dx_3 = new QLineEdit(page_6);
        dx_3->setObjectName(QStringLiteral("dx_3"));
        dx_3->setGeometry(QRect(90, 80, 41, 31));
        dx_4 = new QLabel(page_6);
        dx_4->setObjectName(QStringLiteral("dx_4"));
        dx_4->setGeometry(QRect(200, 80, 31, 21));
        label_29 = new QLabel(page_6);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(60, 80, 31, 21));
        dx_1 = new QLabel(page_6);
        dx_1->setObjectName(QStringLiteral("dx_1"));
        dx_1->setGeometry(QRect(200, 40, 31, 21));
        label_28 = new QLabel(page_6);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(30, 0, 211, 21));
        label_21 = new QLabel(page_6);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(100, 130, 21, 21));
        toolBox->addItem(page_6, QStringLiteral("Custom Line"));
        page_5 = new QWidget();
        page_5->setObjectName(QStringLiteral("page_5"));
        digButton = new QPushButton(page_5);
        digButton->setObjectName(QStringLiteral("digButton"));
        digButton->setGeometry(QRect(320, 160, 95, 31));
        label_24 = new QLabel(page_5);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(130, 30, 31, 21));
        digV0 = new QLineEdit(page_5);
        digV0->setObjectName(QStringLiteral("digV0"));
        digV0->setGeometry(QRect(80, 80, 131, 33));
        label_26 = new QLabel(page_5);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(20, 0, 211, 21));
        dm = new QLineEdit(page_5);
        dm->setObjectName(QStringLiteral("dm"));
        dm->setGeometry(QRect(80, 30, 41, 31));
        label_25 = new QLabel(page_5);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(50, 30, 31, 21));
        dc = new QLineEdit(page_5);
        dc->setObjectName(QStringLiteral("dc"));
        dc->setGeometry(QRect(160, 30, 41, 31));
        label_22 = new QLabel(page_5);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(60, -40, 101, 21));
        QFont font;
        font.setBold(true);
        font.setUnderline(true);
        font.setWeight(75);
        label_22->setFont(font);
        label_20 = new QLabel(page_5);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(40, 90, 21, 21));
        toolBox->addItem(page_5, QStringLiteral("Linear Equation"));
        page = new QWidget();
        page->setObjectName(QStringLiteral("page"));
        label_31 = new QLabel(page);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(10, 0, 321, 21));
        label = new QLabel(page);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 50, 31, 21));
        label_2 = new QLabel(page);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(80, 50, 31, 21));
        label_7 = new QLabel(page);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(120, 50, 16, 21));
        label_17 = new QLabel(page);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(170, 50, 31, 21));
        label_23 = new QLabel(page);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(180, 50, 16, 21));
        quadA = new QLineEdit(page);
        quadA->setObjectName(QStringLiteral("quadA"));
        quadA->setGeometry(QRect(40, 50, 41, 33));
        quadB = new QLineEdit(page);
        quadB->setObjectName(QStringLiteral("quadB"));
        quadB->setGeometry(QRect(130, 50, 41, 33));
        quadC = new QLineEdit(page);
        quadC->setObjectName(QStringLiteral("quadC"));
        quadC->setGeometry(QRect(190, 50, 41, 33));
        label_32 = new QLabel(page);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(10, 120, 66, 21));
        quadV0 = new QLineEdit(page);
        quadV0->setObjectName(QStringLiteral("quadV0"));
        quadV0->setGeometry(QRect(50, 120, 113, 33));
        pushButton_5 = new QPushButton(page);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(340, 160, 95, 31));
        toolBox->addItem(page, QStringLiteral("Quadratic Equation"));
        pushButton_4 = new QPushButton(centralWidget);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(920, 220, 95, 31));
        QFont font1;
        font1.setBold(true);
        font1.setWeight(75);
        pushButton_4->setFont(font1);
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(540, 110, 66, 21));
        frame = new QFrame(centralWidget);
        frame->setObjectName(QStringLiteral("frame"));
        frame->setGeometry(QRect(800, 20, 171, 181));
        QFont font2;
        font2.setStrikeOut(false);
        font2.setKerning(true);
        frame->setFont(font2);
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        radioM = new QRadioButton(frame);
        radioM->setObjectName(QStringLiteral("radioM"));
        radioM->setGeometry(QRect(30, 140, 110, 26));
        radioJ = new QRadioButton(frame);
        radioJ->setObjectName(QStringLiteral("radioJ"));
        radioJ->setGeometry(QRect(30, 20, 110, 26));
        radioG = new QRadioButton(frame);
        radioG->setObjectName(QStringLiteral("radioG"));
        radioG->setGeometry(QRect(30, 60, 110, 26));
        radioS = new QRadioButton(frame);
        radioS->setObjectName(QStringLiteral("radioS"));
        radioS->setGeometry(QRect(30, 100, 110, 26));
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(540, 40, 66, 21));
        size = new QLineEdit(centralWidget);
        size->setObjectName(QStringLiteral("size"));
        size->setGeometry(QRect(630, 40, 113, 33));
        gavsBar = new QProgressBar(centralWidget);
        gavsBar->setObjectName(QStringLiteral("gavsBar"));
        gavsBar->setGeometry(QRect(550, 220, 211, 31));
        gavsBar->setValue(24);
        gavsBar->setTextVisible(false);
        looper = new QLineEdit(centralWidget);
        looper->setObjectName(QStringLiteral("looper"));
        looper->setGeometry(QRect(630, 110, 113, 33));
        pushButton_2 = new QPushButton(centralWidget);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(770, 220, 131, 31));
        label_30 = new QLabel(centralWidget);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(530, 10, 66, 21));
        label_30->setFont(font);
        interact = new QPushButton(centralWidget);
        interact->setObjectName(QStringLiteral("interact"));
        interact->setGeometry(QRect(950, 280, 95, 31));
        origin = new QLabel(centralWidget);
        origin->setObjectName(QStringLiteral("origin"));
        origin->setGeometry(QRect(505, 815, 21, 21));
        maxX = new QLabel(centralWidget);
        maxX->setObjectName(QStringLiteral("maxX"));
        maxX->setGeometry(QRect(1010, 820, 42, 21));
        maxY = new QLabel(centralWidget);
        maxY->setObjectName(QStringLiteral("maxY"));
        maxY->setGeometry(QRect(487, 310, 31, 21));
        MainWindow->setCentralWidget(centralWidget);
        line->raise();
        line_2->raise();
        groupBox->raise();
        gavsLabel->raise();
        tab2->raise();
        tab1->raise();
        toolBox->raise();
        pushButton_4->raise();
        label_4->raise();
        frame->raise();
        label_3->raise();
        size->raise();
        gavsBar->raise();
        looper->raise();
        pushButton_2->raise();
        label_30->raise();
        interact->raise();
        origin->raise();
        maxY->raise();
        maxX->raise();
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1059, 27));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        toolBox->setCurrentIndex(2);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0));
        gavsLabel->setText(QString());
        tab1->setText(QApplication::translate("MainWindow", "1", 0));
        tab2->setText(QApplication::translate("MainWindow", "2", 0));
        pushButton->setText(QApplication::translate("MainWindow", "Add", 0));
        radioX->setText(QApplication::translate("MainWindow", "X parallel", 0));
        radioY->setText(QApplication::translate("MainWindow", "Y parallel", 0));
        label_5->setText(QApplication::translate("MainWindow", "Point:", 0));
        label_6->setText(QApplication::translate("MainWindow", "V0:", 0));
        toolBox->setItemText(toolBox->indexOf(page_2), QApplication::translate("MainWindow", "Simple Bound", 0));
        radioFilled->setText(QApplication::translate("MainWindow", "Filled", 0));
        radioHollow->setText(QApplication::translate("MainWindow", "Hollow", 0));
        label_9->setText(QApplication::translate("MainWindow", "Y:", 0));
        label_11->setText(QApplication::translate("MainWindow", "Radius: ", 0));
        pushButton_3->setText(QApplication::translate("MainWindow", "Add", 0));
        label_10->setText(QApplication::translate("MainWindow", "Centre:", 0));
        label_8->setText(QApplication::translate("MainWindow", "X:", 0));
        label_12->setText(QApplication::translate("MainWindow", "V0:", 0));
        toolBox->setItemText(toolBox->indexOf(page_3), QApplication::translate("MainWindow", "Radial Bound", 0));
        recButoon->setText(QApplication::translate("MainWindow", "Add", 0));
        radioHollow_2->setText(QApplication::translate("MainWindow", "Hollow", 0));
        label_15->setText(QApplication::translate("MainWindow", "X:", 0));
        width->setText(QString());
        label_16->setText(QApplication::translate("MainWindow", "Origin", 0));
        label_14->setText(QApplication::translate("MainWindow", "Y:", 0));
        label_19->setText(QApplication::translate("MainWindow", "height:", 0));
        radioFilled_2->setText(QApplication::translate("MainWindow", "Filled", 0));
        label_13->setText(QApplication::translate("MainWindow", "V0:", 0));
        label_18->setText(QApplication::translate("MainWindow", "length:", 0));
        toolBox->setItemText(toolBox->indexOf(page_4), QApplication::translate("MainWindow", "Rectangular Bound", 0));
        digButton_2->setText(QApplication::translate("MainWindow", "Add", 0));
        label_27->setText(QApplication::translate("MainWindow", "X1 =", 0));
        dx_4->setText(QApplication::translate("MainWindow", "Y2=", 0));
        label_29->setText(QApplication::translate("MainWindow", "X2=", 0));
        dx_1->setText(QApplication::translate("MainWindow", "Y1=", 0));
        label_28->setText(QApplication::translate("MainWindow", "Using two points as reference", 0));
        label_21->setText(QApplication::translate("MainWindow", "V0:", 0));
        toolBox->setItemText(toolBox->indexOf(page_6), QApplication::translate("MainWindow", "Custom Line", 0));
        digButton->setText(QApplication::translate("MainWindow", "Add", 0));
        label_24->setText(QApplication::translate("MainWindow", "x +", 0));
        label_26->setText(QApplication::translate("MainWindow", "Straight line of form y = mx+c", 0));
        label_25->setText(QApplication::translate("MainWindow", "y =", 0));
        label_22->setText(QApplication::translate("MainWindow", "Diagonal line", 0));
        label_20->setText(QApplication::translate("MainWindow", "V0:", 0));
        toolBox->setItemText(toolBox->indexOf(page_5), QApplication::translate("MainWindow", "Linear Equation", 0));
        label_31->setText(QApplication::translate("MainWindow", "Quadratic equation of form y = ax^2 + bx + c", 0));
        label->setText(QApplication::translate("MainWindow", "y =", 0));
        label_2->setText(QApplication::translate("MainWindow", "x^2", 0));
        label_7->setText(QApplication::translate("MainWindow", "+", 0));
        label_17->setText(QApplication::translate("MainWindow", "x", 0));
        label_23->setText(QApplication::translate("MainWindow", "+", 0));
        label_32->setText(QApplication::translate("MainWindow", "V0: ", 0));
        pushButton_5->setText(QApplication::translate("MainWindow", "Add", 0));
        toolBox->setItemText(toolBox->indexOf(page), QApplication::translate("MainWindow", "Quadratic Equation", 0));
        pushButton_4->setText(QApplication::translate("MainWindow", "Run", 0));
        label_4->setText(QApplication::translate("MainWindow", "#loops:", 0));
        radioM->setText(QApplication::translate("MainWindow", "Multigrid", 0));
        radioJ->setText(QApplication::translate("MainWindow", "Jacobi", 0));
        radioG->setText(QApplication::translate("MainWindow", "Gauss-Seidel", 0));
        radioS->setText(QApplication::translate("MainWindow", "SOR", 0));
        label_3->setText(QApplication::translate("MainWindow", "Grid size:", 0));
        pushButton_2->setText(QApplication::translate("MainWindow", "Create/Reset", 0));
        label_30->setText(QApplication::translate("MainWindow", "General", 0));
        interact->setText(QApplication::translate("MainWindow", "Interact", 0));
        origin->setText(QString());
        maxX->setText(QString());
        maxY->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
